/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSpeakingRouteImport } from './routes/_authenticated/speaking'
import { Route as AuthenticatedScenarioRouteImport } from './routes/_authenticated/scenario'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated/resume'
import { Route as AuthenticatedMentorRouteImport } from './routes/_authenticated/mentor'
import { Route as AuthenticatedInterviewRouteImport } from './routes/_authenticated/interview'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDailyRouteImport } from './routes/_authenticated/daily'
import { Route as AuthenticatedCareerRouteImport } from './routes/_authenticated/career'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSpeakingRoute = AuthenticatedSpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScenarioRoute = AuthenticatedScenarioRouteImport.update({
  id: '/scenario',
  path: '/scenario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMentorRoute = AuthenticatedMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewRoute = AuthenticatedInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyRoute = AuthenticatedDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCareerRoute = AuthenticatedCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/career': typeof AuthenticatedCareerRoute
  '/daily': typeof AuthenticatedDailyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/scenario': typeof AuthenticatedScenarioRoute
  '/speaking': typeof AuthenticatedSpeakingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/career': typeof AuthenticatedCareerRoute
  '/daily': typeof AuthenticatedDailyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/scenario': typeof AuthenticatedScenarioRoute
  '/speaking': typeof AuthenticatedSpeakingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/career': typeof AuthenticatedCareerRoute
  '/_authenticated/daily': typeof AuthenticatedDailyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/interview': typeof AuthenticatedInterviewRoute
  '/_authenticated/mentor': typeof AuthenticatedMentorRoute
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/scenario': typeof AuthenticatedScenarioRoute
  '/_authenticated/speaking': typeof AuthenticatedSpeakingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/career'
    | '/daily'
    | '/dashboard'
    | '/interview'
    | '/mentor'
    | '/resume'
    | '/roadmap'
    | '/scenario'
    | '/speaking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/career'
    | '/daily'
    | '/dashboard'
    | '/interview'
    | '/mentor'
    | '/resume'
    | '/roadmap'
    | '/scenario'
    | '/speaking'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/career'
    | '/_authenticated/daily'
    | '/_authenticated/dashboard'
    | '/_authenticated/interview'
    | '/_authenticated/mentor'
    | '/_authenticated/resume'
    | '/_authenticated/roadmap'
    | '/_authenticated/scenario'
    | '/_authenticated/speaking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/speaking': {
      id: '/_authenticated/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof AuthenticatedSpeakingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scenario': {
      id: '/_authenticated/scenario'
      path: '/scenario'
      fullPath: '/scenario'
      preLoaderRoute: typeof AuthenticatedScenarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor': {
      id: '/_authenticated/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof AuthenticatedMentorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview': {
      id: '/_authenticated/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof AuthenticatedInterviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily': {
      id: '/_authenticated/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof AuthenticatedDailyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/career': {
      id: '/_authenticated/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof AuthenticatedCareerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCareerRoute: typeof AuthenticatedCareerRoute
  AuthenticatedDailyRoute: typeof AuthenticatedDailyRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInterviewRoute: typeof AuthenticatedInterviewRoute
  AuthenticatedMentorRoute: typeof AuthenticatedMentorRoute
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedScenarioRoute: typeof AuthenticatedScenarioRoute
  AuthenticatedSpeakingRoute: typeof AuthenticatedSpeakingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCareerRoute: AuthenticatedCareerRoute,
  AuthenticatedDailyRoute: AuthenticatedDailyRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInterviewRoute: AuthenticatedInterviewRoute,
  AuthenticatedMentorRoute: AuthenticatedMentorRoute,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedScenarioRoute: AuthenticatedScenarioRoute,
  AuthenticatedSpeakingRoute: AuthenticatedSpeakingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
